### ISSUE TITLE
Will the linux scripts work with Nitrokey

### ISSUE THREAD

**Issue by cmonty14** [JanMosigItemis/yubiset#3]
Hi Jan,
can you confirm if your scripts will work with other security keys, e.g. Nitrokey?

Regards
Thomas

**Comment by JanMosigItemis** [comment]
Sry, I cannot confirm this. I have never tried them with Nitrokey.

However, I guess chances are that they actually will work with any device that implements the OpenPGP card standard appropriately (which Nitrokey does), because the scripts do use gpg and other non device specific tooling for their work.

I'd say: Just give it a try and let me know how it worked out. **But please be careful**: There is absolutely no warranty whatsoever whether or not the scripts cause data loss.

**Edit**
Argh, I forgot to mention: The key reset script might be device specific since it does manipulate the device on a binary level, so please watch out!
