### ISSUE TITLE
Error in windows batch "yubiset.bat": SAP was unexpected at this time. | branding.bat has problems with special characters

### ISSUE THREAD

**Issue by cmonty14** [JanMosigItemis/yubiset#4]
Hi Jan,
I run script \windows\batch\yubiset.bat in CMD (in Windows 10) and get this error:
SAP was unexpected at this time.

I have attached a screeshot of CMD and the content of branding.bat.

Can you please assist solving this issue?

THX
![2020-02-20_14-34-01](https://user-images.githubusercontent.com/12523591/74939107-9b89a600-53ef-11ea-9638-f169049ecd78.png)
![2020-02-20_14-33-37](https://user-images.githubusercontent.com/12523591/74939109-9cbad300-53ef-11ea-957c-32f800c8c498.png)

**Comment by JanMosigItemis** [comment]
Thx for the report, I'll look into the issue. From a quick view it may be that using "special" characters like "(" in branding.bat confuses the batch processor.

**Comment by cmonty14** [comment]
I can confirm that the issue is related to branding.bat.
After deleting `(something)` from line `set branded_user_comment=` the script works w/o issues.

**Comment by JanMosigItemis** [comment]
The problem was: gpg does not seem to support paranthesis in key comments. As a quick fix I did include several hints on this in the documentation and a little sanitation (remove paranthesis) into the scripts.

Espacially on Windows: Please be aware when using special characters within the branding scripts and in user inputs in general.
